### ISSUE TITLE
how is supposed to be used?

### ISSUE THREAD

**Issue by Kon-Xen** [MortalFlesh/csv-exporter#2]
Hello, I'm not sure how i'm supposed to  use the exporter. What dependencies are needed? the filename , header and 2 callables ? 
by 'columns...' we mean the array ? 

Thanks
K

**Comment by MortalFlesh** [comment]
Hello,

I will try to update readme by the following explanation soon.

Firstly, I will explain, what is in the Readme now.
```php
return (new StreamedResponseFactory(/* ...dependencies */)) // from ->get('service')
    ->createCsv(
        'filename.csv',
        [
            'columns...',
        ],
        function ($offset, $bulk) use ($repository) {
            return $repository->findBulkForExport($offset, $bulk);
        },
        function (array $row) {
            return [
                $row['key'],
            ];
        }
    );
```

First line is getting an instance of the `StreamedResponseFactory`, which will generate the csv stream output.
- you can either instantiate it by yourself, providing all its dependencies, which are `DataStreamGenerator` service, which has its own dependencies, ...
```php
new StreamedResponseFactory(/* ...dependencies */))
```
   - which I **DO NOT** recommend

- or you can use a dependency injection from the Symfony, which will autowire all its dependencies for you
    - but since this is just a library and not a Symfony bundle, you have to register your service by yourself

    - if you are using a yaml configuration, it would look like this:
    ```yaml
    services:
        # default configuration for services in *this* file
        _defaults:
            autowire: true      # Automatically injects dependencies in your services.
            autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        MF\CSVExporter\Factory\StreamedResponseFactory: ~
    ```
    - this will register a `StreamedResponseFactory` service and allow you to get it from Symfony Container
    - if you also configure you Controllers to have autowired services as arguments, by following:
    ```yaml
    MyApp\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    ```
    - then you can use it as follows:

---

Let's say, you have an entity:
```php
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="MyApp\Repository\MyEntityRepository")
 */
class MyEntity
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @var string
     */
    private $name;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string|null
     */
    private $description;

    // ... constructor, getters, setters, whatever ...
}
```

Repository for that entity:
```php
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

class MyEntityRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, MyEntity::class);
    }

    public function findBulkForExport(int $offset, int $limit): array
    {
        return $this->createQueryBuilder('e')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getArrayResult();     // we do not need hydrated entities, just a raw array data
    }
}
```

```php
class MyController extends AbstractController
{
    public function exportAction(StreamedResponseFactory $factory, MyEntityRepository $repository) {
        return $factory->createCsv(
            'file_name.csv',    // whatever you want for a result csv file
            ['id', 'name', 'description'],     // columns, for the csv file
            function (int $offset, int $limit) use ($repository): array {
                return $repository->findBulkForExport($offset, $limit);
            },
            function (array $row): array {      // this function will be called for every single Row in the bulk to format the output
                return [
                    $row['id'],
                    $row['name'],
                    $row['description'] ?? '-empty description-',  // since description is nullable, we can add some default perhaps
                ];
            }
        )
    }
}
```

I write it down just here as example, so I didn't actually run it, but it should produce a csv file as follows.
For entities:
- { id: 1, name: "first", description: null }
- { id: 2, name: "second", description: "second entity" }

```csv
id, name, description
1, first, -empty-description-
2, second, second entity
```

I hope it will help and clarify how to use this :)
